---
title: "mores tests"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
library(emphasis)
```


### a first simple test on NHPP

```{r, e1}
btdd = 10
pars = c(1,0.1,20)
g_fs <- function(t,mu,r,s){   ## g of first missing speciation
  rate = s*(1-exp(-mu*(r-t)))
  int = s*(t-(exp(-r*mu)/mu)*(exp(t*mu)-1))
  prob = rate*exp(-int)
  return(prob)
}

time = seq(0,btdd[1],by=0.1)
g = g_fs(time,mu=pars[2],r=btdd[1],s=2*(pars[1]-(pars[1]-pars[2])*2/pars[3]))
s = sim.sct(btdd,pars,m=10000,print = F)
hist(s$fms,prob=TRUE,breaks = 80)
lines(time,g)

```

```{r, e2}
btdd = 5
pars = c(1,0.1,20)
time = seq(0,btdd[1],by=0.1)
g = g_fs(time,mu=pars[2],r=btdd[1],s=2*(pars[1]-(pars[1]-pars[2])*2/pars[3]))
s = sim.sct(btdd,pars,m=10000,print = F)
hist(s$fms,prob=TRUE,breaks = 80)
lines(time,g)

```


```{r, e3}
btdd = 2
pars = c(1,0.1,20)
time = seq(0,btdd[1],by=0.1)
g = g_fs(time,mu=pars[2],r=btdd[1],s=2*(pars[1]-(pars[1]-pars[2])*2/pars[3]))
s = sim.sct(btdd,pars,m=100000,print = F)
hist(s$fms,prob=TRUE,breaks = 80)
lines(time,g)
```


### a little more complex tree

```{r, e4}
g_fs2 <- function(t,mu,r,s,bk){   ## g of first missing speciation
  if(t<bk){
    rate = s*(1-exp(-mu*(r-t)))
    int = s*(t-(exp(-r*mu)/mu)*(exp(t*mu)-1))
    prob = rate*exp(-int)
  }else{
    int1 = s*(bk-(exp(-r*mu)/mu)*(exp(bk*mu)-1))
    s2=3*(pars[1]-(pars[1]-pars[2])*3/pars[3])
    rate = s2*(1-exp(-mu*(r-t)))
    int2 = s2*(t-bk-(exp(-r*mu)/mu)*(exp(t*mu)-exp(bk*mu)))
    prob = rate*exp(-int1)*exp(-int2)
  }
  return(prob)
}


btdd = c(10,5)
s = sim.sct(btdd,pars,m=10000,print = F)
time = seq(0,btdd[1],by=0.01)
i=1
g = NULL
for(ti in time){
  g[i] = g_fs2(ti,mu=pars[2],r=btdd[1],s=2*(pars[1]-(pars[1]-pars[2])*2/pars[3]),bk=btdd[2])
  i = i+1
}

hist(s$fms,prob=TRUE,breaks = 80)
lines(time,g)

```


```{r, e5}
btdd = c(4,2)
s = sim.sct(btdd,pars,m=100000,print = F)
time = seq(0,btdd[1],by=0.01)
i=1
g = NULL
for(ti in time){
  g[i] = g_fs2(ti,mu=pars[2],r=btdd[1],s=2*(pars[1]-(pars[1]-pars[2])*2/pars[3]),bk=btdd[2])
  i = i+1
}

hist(s$fms,prob=TRUE,breaks = 80)
lines(time,g)

```

