---
title: "Sept 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Given an observed tree $y$, the Monte-Carlo approximation of the likelihood would be defined as 

$$ L(y | \theta) = \frac{1}{m}\sum_{i=1}^m f(x_i,y|\theta) $$

where $x_i$ are complete trees sampled from the conditional distribution $f(x|y,\theta)$. When the complete trees are sampled from another distribution $g(x|y,\theta)$, the approximation would be 

$$ L(y | \theta) = \frac{1}{m}\sum_{i=1}^m f(x_i,y|\theta)\frac{1}{g(x_i|y,\theta)} $$
or $L(y|\theta)=\bar{w}$, where $w = (w_1,...,w_m)$ and $w_i = \frac{f(x_i,y|\theta)}{f(x_i,y|\theta)}$. 

Given that on the DDD case we can calculate directly $L(y | \theta)$ we tested on previous meeting if this equality holds empirically, but unfortunetelly it is only true when the extinction rate $\mu_0$ is zero. Assuming that the DDD calculation of $L(y | \theta)$ is correct, and given that it seems that $f(x_i,y|\theta)$ is correct too, we suspect that either the calculation of $g(x_i,y|\theta)$ or the data augmentation algorithm is not completelly correct. 


To test if the distribution $g(x_i,y|\theta)$ is consistent with the data augmentation algorithm we look at statistics that summarize the performance of it. On the meeting we showed that the first missing speciation time show consistency, and we pointed out the difficulties of observing at the number of missing speciations (dimension). For the next meeting we would like to test second missing speciation and first extinction. We also want to observe the case of constant rates, and lastly we discussed further on how to observe at the dimension as is quite an informative statistics. 


