---
title: "23Oct2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(emphasis)
```


$$ f(y | x=T, \theta) =  

\begin{cases}
    e^{-2\lambda T} & \text{if } brts(y) = T \\
    f_1(y|x=CT,\theta) & \text{if } brts(y) = (t_1,t_2,T) \\
    f_2(y|x=CT,\theta) & \text{if } brts(y) = (t_1,t_2,t_3,t_4,T)
\end{cases}

$$
where 


\begin{equation}
\begin{split}
f_2(y|x=CT,\theta) = & -\frac{e^{s_2}}{s_4(s_4-s_3)(s_3-s_2)(s_2-s_1)}(e^{T(s_2-s_1)}-1) \\
 &+\frac{e^{-s_2}}{s_4(s_4-s_3)(s_3-s_2)(s_3-s_1)}(e^{T(s_3-s_1)}-1)\\
  &+\frac{e^{-s_3}}{s_4(s_4-s_3)(s_4-s_2)(s_2-s_1)}(e^{T(s_2-s_1)}-1)\\
   &-\frac{e^{-s_2}}{s_4(s_4-s_3)(s_4-s_2)(s_4-s_1)}(e^{T(s_4-s_1)}-1)\\
    &-\frac{e^{-s_4}}{s_4s_3(s_3-s_2)(s_2-s_1)}(e^{T(s_2-s_1)}-1)\\
     &+\frac{e^{-s_2}}{s_4s_3(s_3-s_2)(s_3-s_1)}(e^{T(s_3-s_1)}-1)\\
      &-\frac{e^{-s_3}}{s_4s_3(s_3-s_2)(s_2-s_1)}(e^{T(s_2-s_1)}-1)\\
       &-\frac{e^{-s_2}}{s_4s_3s_2s_1}(e^{-s_1T}-1)\\
 &-\frac{1}{s_4(s_4-s_3)s_2(s_2-s_1)}(e^{-s_1T}-1) \}
\end{split}
\end{equation}

```{r}
spec2 <- function(s,CT){
  out = -(exp(-s[2]*CT)/(s[4]*(s[4]-s[3])*(s[3]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1)+
      (exp(-s[3]*CT)/(s[4]*(s[4]-s[3])*(s[3]-s[2])*(s[3]-s[1])))*(exp(CT*(s[3]-s[1]))-1) +
    (exp(-s[2]*CT)/(s[4]*(s[4]-s[3])*(s[4]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
    -(exp(s[4]*CT)/(s[4]*(s[4]-s[3])*(s[4]-s[2])*(s[4]-s[1])))*(exp(CT*(s[4]-s[1]))-1) +
    -(exp(-s[2]*CT)/(s[4]*s[3]*(s[3]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
    (exp(-s[3]*CT)/(s[4]*s[3]*(s[3]-s[2])*(s[3]-s[1])))*(exp(CT*(s[3]-s[1]))-1) +
    -(exp(-s[2]*CT)/(s[4]*s[3]*s[2]*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
    -(1/(s[4]*s[3]*s[2]*s[1]))*(exp(-CT*s[1])-1)
  if(s[3]==s[1]){
    out = -(exp(-s[2]*CT)/(s[4]*(s[4]-s[3])*(s[3]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1)+
      (exp(-s[3]*CT)/(s[4]*(s[4]-s[3])*(s[3]-s[2])))*(CT) +
      (exp(-s[2]*CT)/(s[4]*(s[4]-s[3])*(s[4]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
      -(exp(s[4]*CT)/(s[4]*(s[4]-s[3])*(s[4]-s[2])*(s[4]-s[1])))*(exp(CT*(s[4]-s[1]))-1) +
      -(exp(-s[2]*CT)/(s[4]*s[3]*(s[3]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
      (exp(-s[3]*CT)/(s[4]*s[3]*(s[3]-s[2])))*(CT) +
      -(exp(-s[2]*CT)/(s[4]*s[3]*s[2]*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
      -(1/(s[4]*s[3]*s[2]*s[1]))*(exp(-CT*s[1])-1)
  }
  return(out)
}
```


```{r}
spec1 <- function(s,CT){
  out = (exp(-s[3]*CT)/(s[3]-s[2])) * ( (exp(CT*(s[3]-s[2]))/(s[2]-s[1]))*(exp(CT*(s[2]-s[1]))-1) +
                              - (1/(s[3]-s[1]))*(exp(CT*(s[3]-s[1]))-1) )
  if(s[1]==s[3]){
    out = (exp(-s[3]*CT)/(s[3]-s[2])) * ( (exp(CT*(s[3]-s[2]))/(s[2]-s[1]))*(exp(CT*(s[2]-s[1]))-1) +
                                            - (CT-1) )
  }
  return(out)
}

f.marg2S <- function(CT,lambda,mu){
  s1 = c(2,3,4,3)*c(lambda,lambda+mu,mu,mu)
  s2 = c(2,3,2,3)*c(lambda,lambda+mu,lambda,mu)
  s3 = c(2,3,2)*c(lambda,lambda+mu,lambda)
  out = spec2(s1,CT)*(lambda/(lambda+mu))+spec2(s2,CT)*(mu/(lambda+mu))+spec1(s3,CT)+exp(-ct*2*lambda)
  return(out)
}

```







## Dendroica case 



```{r cars, eval=F}
### Method 1: uniform

sim.extinct.alt <- function(brts,cte=10){
  N = length(brts)+1
  Ne = sample(0:(cte*N),1)
  ms = runif(Ne,min=0,max=brts[1])
  me = runif(Ne,min=ms,max=brts[1])
  to = c(rep(1,Ne),rep(0,Ne))
  df = data.frame(bt = c(ms,me),bte=c(me,rep(Inf,Ne)),to=to)
  df = rbind(df,data.frame(bt=brts,to=rep(2,length(brts)),bte=rep(Inf,length(brts))))
  df = df[order(df$bt),]
  df$t.ext = df$bte-df$bt
  return(df)
}

g_samp <- function(df,cte){
  last = dim(df)[1]
  ct = df[last,1]
  N = sum(df$to==2)+1
  M = N*cte
  Ne = sum(df$to==0)
  subdf = df[df$to==1,]
  Ts = ct-subdf$bt
  to = df$to[-last]
  to[to==2] = 1
  n = c(2,2+cumsum(to)+cumsum(to-1))
  n = n[df$to==1]
  #  density = (1/(M+1))*((1/ct)^Ne)*prod(1/Ts)*prod(1/n)
  log_dens = -log(M+1)-Ne*log(ct)-sum(log(Ts))-sum(log(n))+lgamma(Ne+1)
  #log_dens = -log(M+1)-2*Ne*log(ct)-sum(log(n))
  return(log_dens)
}


f.hat <- function(brts,pars,cte=10,m=100){
  f.joint = vector(mode="numeric",length=m)
  g.samp = vector(mode="numeric",length=m)
  for(i in 1:m){
    df = sim.extinct.alt(brts,cte=cte)
    f.joint[i] = -emphasis::nllik.tree(pars,tree=emphasis::df2tree(df,pars))
    g.samp[i] = g_samp(df,cte=cte)
  }
  f_hat = log(mean(exp(f.joint-g.samp)))
  return(f_hat)
}

##### Method 2: Poisson

sim.extinct.alt2 <- function(brts,pars){
  Ne = rpois(1,pars[1]-pars[2])
  ms = runif(Ne,min=0,max=brts[1])
  me = runif(Ne,min=ms,max=brts[1])
  to = c(rep(1,Ne),rep(0,Ne))
  df = data.frame(bt = c(ms,me),bte=c(me,rep(Inf,Ne)),to=to)
  df = rbind(df,data.frame(bt=brts,to=rep(2,length(brts)),bte=rep(Inf,length(brts))))
  df = df[order(df$bt),]
  df$t.ext = df$bte-df$bt
  return(df)
}

g_samp2 <- function(df,pars){
  last = dim(df)[1]
  ct = df[last,1]
  Ne = sum(df$to==0)
  subdf = df[df$to==1,]
  Ts = ct-subdf$bt
  to = df$to[-last]
  to[to==2] = 1
  n = c(2,2+cumsum(to)+cumsum(to-1))
  n = n[df$to==1]
  #  density = (1/(M+1))*((1/ct)^Ne)*prod(1/Ts)*prod(1/n)
  log_dens = dpois(Ne,lambda = pars[1]-pars[2],log=TRUE)-Ne*log(ct)-sum(log(Ts))-sum(log(n))+lgamma(Ne+1)
  #log_dens = -log(M+1)-2*Ne*log(ct)-sum(log(n))
  return(log_dens)
}


f.hat2 <- function(brts,pars,m=100){
  f.joint = vector(mode="numeric",length=m)
  g.samp = vector(mode="numeric",length=m)
  for(i in 1:m){
    df = sim.extinct.alt2(brts,pars=pars)
    f.joint[i] = -emphasis::nllik.tree(pars,tree=emphasis::df2tree(df,pars))
    g.samp[i] = g_samp2(df,pars=pars)
  }
  f_hat = log(mean(exp(f.joint-g.samp)))
  return(f_hat)
}
############################
# Consider a single case

pars = c(3,1,9e+9999999)
brts = 2
f.hat(brts,pars,m = 1000)
f.hat2(brts,pars,m = 1000)


###########################################################
# Consider varying mu

n.sim<-25
cte = 10
mu <- seq(0.001,2.99,length=n.sim)
#brts = 2
#dendroica
btdd = c(4.9999999998,4.806886544,4.70731246478,4.50735197578,4.37856240588,4.29594855558,4.19207515688,4.18261061218,4.11238451758,4.09640902445,3.81723693538,3.71143733895,3.48845298905,3.25729503338,3.11613886835,2.64829864145,2.63531839038,2.37990087748,1.82721570435,0.83704715535,0.64242044758,0.56121103655,0.356333544350001,0.346462849050001)
brts = btdd
n.gsim <- 1000
f_hat<-NULL
f.true<-NULL
f_hat2 <- NULL
f_hat3 <- NULL
#pars = c(3,1,9e+9999999)
pars = c(3,1,24.5)
for (i in 1:n.sim){
  pars[2] = mu[i]
  f_hat[i] <- f.hat(brts,pars,m = n.gsim,cte = cte)
  f_hat3[i] <- f.hat2(brts,pars,m = n.gsim)
  f.true[i]<- DDD:::dd_loglik(pars1 = pars, pars2 = pars2,brts = brts, missnumspec = 0)
  S = emphasis:::sim.sct(brts,pars,1000,print = FALSE)
  f_hat2[i] <- log(mean(S$w))
}
plot(mu,f.true,type="l",ylim=c(min(f_hat,f_hat3),max(f.true,f_hat,f_hat2,f_hat3)))
points(mu,f_hat)
points(mu,f_hat2,col="red")
points(mu,f_hat3,col="blue")
```


## constant rates likelihood
