---
title: "2 speciations allowed"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(emphasis)
```


```{r}
f.joint <- function(x,lambda,mu){
  tm = x$brts
  M = (ncol(tm)-1)/2
  ans<-NULL
  pars = c(lambda,mu,9e+99)
  if (is.vector(tm)){
    tm<-matrix(tm,nrow=1)
  }
  for (i in 1:nrow(tm)){
    wt = no.na(diff(c(0,x$brts[i,])))
    to = no.na(x$to[i,])
    t.ext = no.na(x$t.ext[i,])
    e = (to==1 & t.ext < 9e+8) # speciation of missing species
    if(length(wt) == length(to)) to = to[-length(to)]
    tot = to
    to[to==2] = 1
    n = c(2,2+cumsum(to)+cumsum(to-1))
    mu = pars[2]
    lambda = lambda.dd(pars,n)
    rho = pmax(lambda[-length(lambda)]*to+mu*(1-to),0)
    sigma = (lambda + mu)*n
    sigma[n==2] = lambda[n==2]*2
    if(sum(to)>=M){
      stopspec = min(which(cumsum(to)==M))
      sigma[(stopspec+1):length(sigma)] = mu*n[(stopspec+1):length(sigma)]
      if(sum(1-to)==M){
        sigma = sigma[-length(sigma)]
        wt = wt[-length(wt)]
      }
    }
    ans[i] = sum(-sigma*wt)+sum(log(rho))
  }
  return(ans)
}

spec2 <- function(s,CT){
  out = -(exp(-s[2]*CT)/(s[4]*(s[4]-s[3])*(s[3]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1)+
      (exp(-s[3]*CT)/(s[4]*(s[4]-s[3])*(s[3]-s[2])*(s[3]-s[1])))*(exp(CT*(s[3]-s[1]))-1) +
    (exp(-s[2]*CT)/(s[4]*(s[4]-s[3])*(s[4]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
    -(exp(s[4]*CT)/(s[4]*(s[4]-s[3])*(s[4]-s[2])*(s[4]-s[1])))*(exp(CT*(s[4]-s[1]))-1) +
    -(exp(-s[2]*CT)/(s[4]*s[3]*(s[3]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
    (exp(-s[3]*CT)/(s[4]*s[3]*(s[3]-s[2])*(s[3]-s[1])))*(exp(CT*(s[3]-s[1]))-1) +
    -(exp(-s[2]*CT)/(s[4]*s[3]*s[2]*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
    -(1/(s[4]*s[3]*s[2]*s[1]))*(exp(-CT*s[1])-1)
  if(s[3]==s[1]){
    out = -(exp(-s[2]*CT)/(s[4]*(s[4]-s[3])*(s[3]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1)+
      (exp(-s[3]*CT)/(s[4]*(s[4]-s[3])*(s[3]-s[2])))*(CT) +
      (exp(-s[2]*CT)/(s[4]*(s[4]-s[3])*(s[4]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
      -(exp(s[4]*CT)/(s[4]*(s[4]-s[3])*(s[4]-s[2])*(s[4]-s[1])))*(exp(CT*(s[4]-s[1]))-1) +
      -(exp(-s[2]*CT)/(s[4]*s[3]*(s[3]-s[2])*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
      (exp(-s[3]*CT)/(s[4]*s[3]*(s[3]-s[2])))*(CT) +
      -(exp(-s[2]*CT)/(s[4]*s[3]*s[2]*(s[2]-s[1])))*(exp(CT*(s[2]-s[1]))-1) +
      -(1/(s[4]*s[3]*s[2]*s[1]))*(exp(-CT*s[1])-1)
  }
  return(out)
}

spec1 <- function(s,CT){
  out = (exp(-s[3]*CT)/(s[3]-s[2])) * ( (exp(CT*(s[3]-s[2]))/(s[2]-s[1]))*(exp(CT*(s[2]-s[1]))-1) +
                              - (1/(s[3]-s[1]))*(exp(CT*(s[3]-s[1]))-1) )
  if(s[1]==s[3]){
    out = (exp(-s[3]*CT)/(s[3]-s[2])) * ( (exp(CT*(s[3]-s[2]))/(s[2]-s[1]))*(exp(CT*(s[2]-s[1]))-1) +
                                            - (CT-1) )
  }
  return(out)
}

f.marg2S <- function(CT,lambda,mu){
  s1 = c(2,3,4,3)*c(lambda,lambda+mu,mu,mu)
  s2 = c(2,3,2,3)*c(lambda,lambda+mu,lambda,mu)
  s3 = c(2,3,2)*c(lambda,lambda+mu,lambda)
  out = spec2(s1,CT)*(lambda/(lambda+mu))+spec2(s2,CT)*(mu/(lambda+mu))+spec1(s3,CT)+exp(-CT*2*lambda)
  return(out)
}

g <- function(x,M){
  ans<-NULL
  n<-nrow(x$brts)
  for (i in 1:n){
    df = data.frame(bt=no.na(x$brts[i,]),bte=no.na(x$t.ext[i,]),to=no.na(x$to[i,]),t.ext=no.na(x$t.ext[i,])-no.na(x$brts[i,]))
    ans[i] = g_samp(df,M)
  }
  return(ans)
}

g_samp <- function(df,M){
  last = dim(df)[1]
  ct = df[last,1]
  Ng = sum(df$to==2) - 1 # number of observed speciations (or given data)
  R = M - Ng
  subdf = df[df$to==1,]
  ms = dim(subdf)[1]
  Ts = ct-subdf$bt
  tempto = df$to
  to = df$to[-last]
  to[to==2] = 1
  n = c(2,2+cumsum(to)+cumsum(to-1))
  n = n[tempto==1 | tempto==0]
  if(R==0){
    log_dens = 0
  }else{
    log_dens = - log(R+1) - ms*log(ct) - sum(log(Ts)) - sum(log(n))
  }
  return(log_dens)
}

sim.extinct.truncdim <- function(brts,M){
  brts = no.na(brts)
  R = M - (length(brts)-1) # maximum possible number of extinctions
  Ne = sample((0:R),1)
  ms = runif(Ne,min=0,max=brts[1])
  me = runif(Ne,min=ms,max=brts[1])
  to = c(rep(1,Ne),rep(0,Ne))
  df = data.frame(bt = c(ms,me),bte=c(me,rep(Inf,Ne)),to=to)
  df = rbind(df,data.frame(bt=brts,to=rep(2,length(brts)),bte=rep(Inf,length(brts))))
  df = df[order(df$bt),]
  df$t.ext = df$bte-df$bt
  return(df)
}

no.na <- function(vector){
  vector[!is.na(vector)]
}


g.sim <- function(x.obs,n=NULL,M){
  if (is.vector(x.obs)){
    x.obs <- matrix(rep(x.obs,each=n),ncol=length(x.obs))
  }
  n <- nrow(x.obs)
  brts <- matrix(nrow=n,ncol=2*M+1)
  to <- matrix(nrow=n,ncol=2*M+1)
  t.ext <- matrix(nrow=n,ncol=2*M+1)
  for (i in 1:n){
    wt = no.na(diff(c(0,x.obs[i,])))
    cs = length(wt)-1 # current speciations
    pm = M - cs  # possible speciations
    if(pm > 0 ){
      df = sim.extinct.truncdim(cumsum(wt),pm)
      brts[i,1:length(df$bt)] = df$bt
      to[i,1:length(df$to)] = df$to
      t.ext[i,1:length(df$to)] = df$t.ext
    }else{
      brts[i,1:length(wt)] = cumsum(wt)
      to[i,1:(length(wt))] = c(rep(2,(length(wt)-1)),2)
      t.ext[i,1:(length(wt))] = c(rep(Inf,(length(wt)-1)),Inf)
    }
  }
  return(list(brts=brts,to=to,t.ext=t.ext))
}

f.sim <- function(n,lambda,mu,CT=2,M){
  TO <- matrix(NA,ncol=2*M+1,nrow=n)
  BRTS <- matrix(NA,ncol=2*M+1,nrow=n)
  T.EXT <- matrix(NA,ncol=2*M+1,nrow=n)
  for (i in 1:n){
    bt = 0
    N = 2
    to = NULL
    brts = NULL
    ns = ne = 0
    t.ext = NULL
    while(bt < CT & ns < M & N > 1){
      time <- rexp(1,N*(lambda+mu))
      bt = bt + time
      to1 = rbinom(1,1,lambda/(lambda+mu))
      if (to1 == 1) {
        N = N + 1
        ns = ns + 1
      } else {
        N = N-1
        ne = ne +1
        if(N>1) t.ext[sample((1:length(t.ext))[t.ext==Inf & to==1],1)] = bt
      }
      t.ext = c(t.ext,Inf)
      brts = c(brts,bt)
      to = c(to,to1)
    }
    while(bt < CT & ne < M & N > 1){
      time <- rexp(1,N*mu)
      bt = bt + time
      if(bt < CT){
        to = c(to,0)
        t.ext = c(t.ext,Inf)
        brts = c(brts,bt)
      }
      N = N-1
      ne = ne+1
      if(bt<CT & N>1) t.ext[sample((1:length(t.ext))[t.ext==Inf & to==1],1)] = bt
    }
    brts=c(brts,CT)
    t.ext = c(t.ext,Inf)
    to = c(to,2)
    BRTS[i,1:length(brts)] = brts
    TO[i,1:length(to)] = to
    T.EXT[i,1:length(to)] = t.ext
  }
  return(list(brts=BRTS,to=TO,t.ext=T.EXT))
}


observe <- function(x){
  tm = x$brts
  ta<-matrix(nrow=nrow(tm),ncol=ncol(tm)-1)
  for(i in 1:nrow(tm)){
    to = x$to[i,]
    to = to[!is.na(to)]
    t.ext = x$t.ext[i,]
    t.ext = t.ext[!is.na(t.ext)]
    brts = x$brts[i,]
    brts = brts[!is.na(brts)]
    obs = c(brts[c((to==1 & t.ext == Inf),F)],brts[length(brts)])
    ta[i,1:length(obs)] = obs
  }
  return(ta)
}

rm_ext <- function(x){
  rm = (x$to[,1] == 0)
  x$brts = x$brts[!rm,]
  x$to = x$to[!rm,]
  x$t.ext = x$t.ext[!rm,]
  return(x)
}


```


```{r cars}
#2 speciations case

n.sim = 4
lambda = 1
mu = 0.3
CT = 2
M = 2

#x.obs<-observe(x)
x.obs <- matrix(nrow=2,ncol=2*M)
x.obs[,1] = CT

f.hat<-NULL
n.sim <- nrow(x.obs)
n.gsim = 100
for (i in 1:n.sim){
  x.ext<-g.sim(x.obs[i,],n=n.gsim,M=M)
  f.hat[i] <- mean(exp(f.joint(x.ext,lambda=lambda,mu=mu)-g(x.ext,M)))
}
f.true<-f.marg2S(CT,lambda,mu)
cbind(f.true,f.hat)
```

