---
title: "03toE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(emphasis)
```




## Large M equivalent to emphasis


```{r}
f.joint <- function(x,lambda,mu,M){
  tm = x$brts
  if (is.vector(tm)){
    tm<-matrix(tm,nrow=1)
  }
  if(is.null(M)) M = (ncol(tm)-1)/2
  ans<-NULL
  pars = c(lambda,mu,9e+99)
  for (i in 1:nrow(tm)){
    wt = no.na(diff(c(0,x$brts[i,])))
    to = no.na(x$to[i,])
    t.ext = no.na(x$t.ext[i,])
    e = (to==1 & t.ext < 9e+8) # speciation of missing species
    if(length(wt) == length(to)) to = to[-length(to)]
    tot = to
    to[to==2] = 1
    n = c(2,2+cumsum(to)+cumsum(to-1))
    mu = pars[2]
    lambda = lambda.dd(pars,n)
    rho = pmax(lambda[-length(lambda)]*to+mu*(1-to),0)
    sigma = (lambda + mu)*n
    sigma[n==2] = lambda[n==2]*2
    if(sum(to)>=M){
      stopspec = min(which(cumsum(to)==M))
      sigma[(stopspec+1):length(sigma)] = mu*n[(stopspec+1):length(sigma)]
      if(sum(1-to)==M){
        sigma = sigma[-length(sigma)]
        wt = wt[-length(wt)]
      }
    }
    ans[i] = sum(-sigma*wt)+sum(log(rho))
  }
  return(ans)
}

f.sim <- function(n,lambda,mu,CT=2,M){
  TO <- matrix(NA,ncol=2*M+1,nrow=n)
  BRTS <- matrix(NA,ncol=2*M+1,nrow=n)
  T.EXT <- matrix(NA,ncol=2*M+1,nrow=n)
  for (i in 1:n){
    bt = 0
    N = 2
    to = NULL
    brts = NULL
    ns = ne = 0
    t.ext = NULL
    while(bt < CT & ns < M & N > 1){
      time <- rexp(1,N*(lambda+mu))
      bt = bt + time
      to1 = rbinom(1,1,lambda/(lambda+mu))
      if (to1 == 1) {
        N = N + 1
        ns = ns + 1
      } else {
        N = N-1
        ne = ne +1
        if(N>1) t.ext[sample((1:length(t.ext))[t.ext==Inf & to==1],1)] = bt
      }
      t.ext = c(t.ext,Inf)
      brts = c(brts,bt)
      to = c(to,to1)
    }
    while(bt < CT & ne < M & N > 1){
      time <- rexp(1,N*mu)
      bt = bt + time
      if(bt < CT){
        to = c(to,0)
        t.ext = c(t.ext,Inf)
        brts = c(brts,bt)
      }
      N = N-1
      ne = ne+1
      if(bt<CT & N>1) t.ext[sample((1:length(t.ext))[t.ext==Inf & to==1],1)] = bt
    }
    brts=c(brts,CT)
    t.ext = c(t.ext,Inf)
    to = c(to,2)
    BRTS[i,1:length(brts)] = brts
    TO[i,1:length(to)] = to
    T.EXT[i,1:length(to)] = t.ext
  }
  return(list(brts=BRTS,to=TO,t.ext=T.EXT))
}

rm_ext <- function(x){
  rm = (x$to[,1] == 0)
  x$brts = x$brts[!rm,]
  x$to = x$to[!rm,]
  x$t.ext = x$t.ext[!rm,]
  return(x)
}

no.na <- function(vector){
  vector[!is.na(vector)]
}
```



Testing if we have the same join likelihood 


```{r}
# TESTING FUNCTIONS
#sampling
set.seed(1)
n.sim = 2
lambda = 1
mu = 0.3
CT = 2
M = 5
x<-f.sim(n.sim,lambda = lambda, mu=mu, CT=CT,M = M)
x = rm_ext(x)
x


# should match
f.joint(x,lambda = lambda, mu=mu, M=100)
tree1 = list(wt=no.na(diff(c(0,x$brts[1,]))),to=no.na(x$to[1,])[-length(no.na(x$to[1,]))])
-nllik.tree(pars = c(lambda,mu,Inf),tree = tree1)
tree2 = list(wt=no.na(diff(c(0,x$brts[2,]))),to=no.na(x$to[2,])[-length(no.na(x$to[2,]))])
-nllik.tree(pars = c(lambda,mu,Inf),tree = tree2)
```

