# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

speciation_r_cpp <- function(tm, tree, pars, soc) {
    .Call(`_emphasis_speciation_r_cpp`, tm, tree, pars, soc)
}

sum_speciation_rate <- function(cbt, tree, pars, soc) {
    .Call(`_emphasis_sum_speciation_rate`, cbt, tree, pars, soc)
}

augment_cpp <- function(brts_in, pars, soc) {
    .Call(`_emphasis_augment_cpp`, brts_in, pars, soc)
}

