# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_n_from_time <- function(bt, input_tree, soc) {
    .Call(`_emphasis_check_n_from_time`, bt, input_tree, soc)
}

augment_cpp2 <- function(brts_in, pars, model, soc) {
    .Call(`_emphasis_augment_cpp2`, brts_in, pars, model, soc)
}

