# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

augment_cpp <- function(brts_in, pars, model, soc) {
    .Call('_emphasis_augment_cpp', PACKAGE = 'emphasis', brts_in, pars, model, soc)
}

loglik_tree_cpp <- function(model, input_pars, input_tree) {
    .Call('_emphasis_loglik_tree_cpp', PACKAGE = 'emphasis', model, input_pars, input_tree)
}

